packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  ddg-search: true
  esbuild: true
  msw: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@assistant-ui/core@0.2.14'
  - '@assistant-ui/react-ai-sdk@1.3.35'
  - '@assistant-ui/store@0.2.16'
  - '@assistant-ui/react-streamdown@0.3.3'
  - '@assistant-ui/react@0.14.18'
  - '@assistant-ui/tap@0.7.1'
