/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as OpsLogRouteImport } from './routes/ops-log'
import { Route as FeedsRouteImport } from './routes/feeds'
import { Route as DailyReportRouteImport } from './routes/daily-report'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedsIndexRouteImport } from './routes/feeds.index'
import { Route as DailyReportIndexRouteImport } from './routes/daily-report.index'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsLogRoute = OpsLogRouteImport.update({
  id: '/ops-log',
  path: '/ops-log',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsRoute = FeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportRoute = DailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIndexRoute = FeedsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedsRoute,
} as any)
const DailyReportIndexRoute = DailyReportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DailyReportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/daily-report': typeof DailyReportRouteWithChildren
  '/feeds': typeof FeedsRouteWithChildren
  '/ops-log': typeof OpsLogRoute
  '/sources': typeof SourcesRoute
  '/wiki': typeof WikiRoute
  '/daily-report/': typeof DailyReportIndexRoute
  '/feeds/': typeof FeedsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/ops-log': typeof OpsLogRoute
  '/sources': typeof SourcesRoute
  '/wiki': typeof WikiRoute
  '/daily-report': typeof DailyReportIndexRoute
  '/feeds': typeof FeedsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/daily-report': typeof DailyReportRouteWithChildren
  '/feeds': typeof FeedsRouteWithChildren
  '/ops-log': typeof OpsLogRoute
  '/sources': typeof SourcesRoute
  '/wiki': typeof WikiRoute
  '/daily-report/': typeof DailyReportIndexRoute
  '/feeds/': typeof FeedsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/daily-report'
    | '/feeds'
    | '/ops-log'
    | '/sources'
    | '/wiki'
    | '/daily-report/'
    | '/feeds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/ops-log'
    | '/sources'
    | '/wiki'
    | '/daily-report'
    | '/feeds'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/daily-report'
    | '/feeds'
    | '/ops-log'
    | '/sources'
    | '/wiki'
    | '/daily-report/'
    | '/feeds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DailyReportRoute: typeof DailyReportRouteWithChildren
  FeedsRoute: typeof FeedsRouteWithChildren
  OpsLogRoute: typeof OpsLogRoute
  SourcesRoute: typeof SourcesRoute
  WikiRoute: typeof WikiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-log': {
      id: '/ops-log'
      path: '/ops-log'
      fullPath: '/ops-log'
      preLoaderRoute: typeof OpsLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds': {
      id: '/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-report': {
      id: '/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof DailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/': {
      id: '/feeds/'
      path: '/'
      fullPath: '/feeds/'
      preLoaderRoute: typeof FeedsIndexRouteImport
      parentRoute: typeof FeedsRoute
    }
    '/daily-report/': {
      id: '/daily-report/'
      path: '/'
      fullPath: '/daily-report/'
      preLoaderRoute: typeof DailyReportIndexRouteImport
      parentRoute: typeof DailyReportRoute
    }
  }
}

interface DailyReportRouteChildren {
  DailyReportIndexRoute: typeof DailyReportIndexRoute
}

const DailyReportRouteChildren: DailyReportRouteChildren = {
  DailyReportIndexRoute: DailyReportIndexRoute,
}

const DailyReportRouteWithChildren = DailyReportRoute._addFileChildren(
  DailyReportRouteChildren,
)

interface FeedsRouteChildren {
  FeedsIndexRoute: typeof FeedsIndexRoute
}

const FeedsRouteChildren: FeedsRouteChildren = {
  FeedsIndexRoute: FeedsIndexRoute,
}

const FeedsRouteWithChildren = FeedsRoute._addFileChildren(FeedsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DailyReportRoute: DailyReportRouteWithChildren,
  FeedsRoute: FeedsRouteWithChildren,
  OpsLogRoute: OpsLogRoute,
  SourcesRoute: SourcesRoute,
  WikiRoute: WikiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
